name: "Extent Report Deployer"
description: "Deploy Extent Reports"
inputs:
  branch:
    description: "Branch to deploy reports"
    required: true
    default: "gh-pages"
  folder:
    description: "Folder containing the reports"
    required: true
    default: "build"
runs:
  using: "composite"
  steps:
    - name: Deploying Reports
      run: |
        echo "Deploying reports from ${{ inputs.folder }} to ${{ inputs.branch }}"
        # Add your deployment logic here
